apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo
spec:
  project: default

  source:
    repoURL: https://github.com/veresattila2002/argocd_app_of_apps.git
    targetRevision: HEAD
    path:  apps
  
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true