apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app-java
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default

  source:
    repoURL: https://github.com/veresattila2002/spring-boot-k8s.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
