apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-platform
  namespace: argo
spec:
  project: default

  source:
    repoURL: https://github.com/veresattila2002/istio_platform_for_argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
